### ISSUE TITLE
[mcd-custom-los r3] Failed to apply optimization log spam

### ISSUE THREAD

**Issue by dreamwhite** [mcdachpappe/android_kernel_oneplus_sdm845#1]
Hi there,
I own a OnePlus 6T with crDroid 7.5 (based on LineageOS) and flashed mcd-custom-los r3 due to some weird behaviour of WiFi handling with the vanilla kernel of crDroid.
While I was on MatLog to check any kind of error, I noticed that when I touch the screen, a logspam of "Failed to apply optimizazion [2,1]" is shown in matlog. Can this error message be suppressed in any way?
Many thanks and don't hesitate to ask for logs :")

**Comment by mcdachpappe** [comment]
Thanks for reporting.

I was able to track down the issue: CONFIG_MSM_PERFORMANCE has to be enabled in order to suppress this log spam. Will be fixed in the next build.
