### ISSUE TITLE
R4 breaks wifi

### ISSUE THREAD

**Issue by akavkl** [mcdachpappe/android_kernel_oneplus_sdm845#2]

**Comment by akavkl** [comment]
Using custom on shapeshift, had no issues with r3

**Comment by radu-v** [comment]
fine here on fajita with crDroid 7.6, mcd custom-los r4, 10.3.11 vendor

**Comment by akavkl** [comment]
I'm on op6 with shapeshift 2.6 10.3.11 firmware

**Comment by mcdachpappe** [comment]
@akavkl any logs?

Join our telegram group at https://t.me/mcd_kernel to grab the latest test build - it includes a fix for broken mac-adresses on some custom roms. Maybe this solves your issue. I can not fix this issue without your feedback,

Regards

**Comment by akavkl** [comment]
Joining telegram
I'll try that test build and gives logs from that version

**Comment by mcdachpappe** [comment]
Fixed in commit https://github.com/mcdachpappe/android_kernel_oneplus_sdm845-r2/commit/185d791b739a106133ddbdaa937c18af53121377
