### ISSUE TITLE
Which installation precedure?

### ISSUE THREAD

**Issue by maichai** [mcdachpappe/android_kernel_oneplus_sdm845#4]
There are a bunch of different installation precedures areound (nethunter pages, XDA forums etc). It is kinda confusing and not everything works with every image. 

I think it would be helpful if there was a pointer to an installation procedure for the OP 6T with LineageOS (18.1) for this nethunter kernel.

**Comment by radu-v** [comment]
you just flash the proper zip (custom or OOS) via TWRP or the FKM app, afaik

**Comment by mcdachpappe** [comment]
'this nethunter kernel' ?

Installation is simple and always the same if a kernel is shipped with anykernel template: Flash the kernel .zip at last, done.

A correct procedure can be:
1. Flash ROM
2. Flash any additions
3. Flash Kernel

I don't see any 'issue' here. Closed
